:: Generated by: https://github.com/swagger-api/swagger-codegen.git
::

@echo off

dotnet restore src\KrisLange.UrlShortener
dotnet build src\KrisLange.UrlShortener
echo Now, run the following to start the project: dotnet run -p src\KrisLange.UrlShortener\KrisLange.UrlShortener.csproj --launch-profile web.
echo.
